# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.

require 'rubygems'
require 'bundler/setup'
Bundler.require

DB = Sequel.connect(ENV.fetch("TEST_DATABASE_URL"))

require 'database_cleaner'
require 'factory_girl'

Dir[File.dirname(__FILE__) + '/../lib/**/*.rb'].each {|file| require file }

FactoryGirl.definition_file_paths = %w{./factories ./test/factories ./spec/factories  }
FactoryGirl.find_definitions

#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Enforce expect syntax
  config.expect_with :rspec do |c|
    c.syntax = :expect
  end

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  # Set up factories
  config.include FactoryGirl::Syntax::Methods

  config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
  end

  config.around(:each) do |example|
    DatabaseCleaner.cleaning do
      example.run
    end
  end
end
